In [ ]:
## 1. Data Import
"""
In this step, the Netflix dataset was imported using Pandas to prepare it for cleaning and analysis.
"""
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/Dataset.csv')

In [ ]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [ ]:
## 2. Dataset Overview
"""
The dataset structure was explored to understand:
- Number of records and columns.
- Data types.
- Available features.
- Data completeness.
"""

'\nThe dataset structure was explored to understand:\n- Number of records and columns.\n- Data types.\n- Available features.\n- Data completeness.\n'

In [ ]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

In [ ]:
# Dataset dimention
df.shape

(8790, 10)

In [ ]:
### Observation
"""
The dataset contains:
- 8,790 records.
- 10 columns.
- 9 categorical columns and 1 numerical column (`release_year`).
- All columns contain complete data with no missing values.

"""

'\nThe dataset contains:\n- 8,790 records.\n- 10 columns.\n- 9 categorical columns and 1 numerical column (`release_year`).\n- All columns contain complete data with no missing values.\n\n'

In [ ]:
## 3. Missing Values Analysis
"""
Missing values were checked to ensure data quality before analysis.

"""

'\nMissing values were checked to ensure data quality before analysis.\n\n'

In [ ]:

#Check missing values
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [ ]:
### Observation

"""
All columns contain 8,790 non-null values.
Therefore, no missing value treatment was required.

"""

'\nAll columns contain 8,790 non-null values.\nTherefore, no missing value treatment was required.\n\n'

In [ ]:
## 4. Duplicate Records Analysis
"""
Duplicate records were checked to identify repeated rows that may affect analysis accuracy.

"""

'\nDuplicate records were checked to identify repeated rows that may affect analysis accuracy.\n'

In [ ]:
# Check complete duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
### Observation
"""
No complete duplicate records were found in the dataset.
Therefore, no rows were removed.
"""

'\nNo complete duplicate records were found in the dataset.\nTherefore, no rows were removed.\n'

In [ ]:
# Check duplicated titles
df[df.duplicated('title', keep=False)].sort_values('title')

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
393,s3997,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"

In [ ]:
### Observation
"""
Some titles appear more than once; however, these records have different show IDs.

Example:
- Same title with different show_id values.

These are not duplicate records because each row represents a separate entry.
Therefore, they were kept.
"""

'\nSome titles appear more than once; however, these records have different show IDs.\n\nExample:\n- Same title with different show_id values.\n\nThese are not duplicate records because each row represents a separate entry.\nTherefore, they were kept.\n'

In [ ]:
## 5. Data Standardization
"""
Text columns were checked and cleaned to remove formatting inconsistencies.

"""

'\nText columns were checked and cleaned to remove formatting inconsistencies.\n\n'

In [ ]:
# Remove extra spaces from text columns
text_columns = df.select_dtypes(include = 'object').columns
for col in text_columns:
    df[col] = df[col].str.strip()

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

In [ ]:
### Country Column Standardization
"""
The country column was checked for:
- Extra spaces.
- Different capitalization formats.

The values were already standardized, so only formatting consistency was ensured.

"""

'\nThe country column was checked for:\n- Extra spaces.\n- Different capitalization formats.\n\nThe values were already standardized, so only formatting consistency was ensured.\n\n'

In [ ]:
df['country'].value_counts()

country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
                  ...
Luxembourg           1
Senegal              1
Belarus              1
Puerto Rico          1
Cyprus               1
Name: count, Length: 86, dtype: int64

In [ ]:
df['country'] = df['country'].str.strip()
df['country'] = df['country'].str.title()

In [ ]:
print("Check the first 10 unique country values to verify consistency after standardization\n")
print(df['country'].unique()[:10])
# Check the frequency of each country category
print("\n  Check distribution")
df['country'].value_counts()

Check the first 10 unique country values to verify consistency after standardization

['United States' 'France' 'Brazil' 'United Kingdom' 'India' 'Germany'
 'Pakistan' 'Not Given' 'China' 'South Africa']

  Check distribution

country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
                  ...
Luxembourg           1
Senegal              1
Belarus              1
Puerto Rico          1
Cyprus               1
Name: count, Length: 86, dtype: int64

In [ ]:
### Rating Column Standardization
"""
The rating column was standardized by:
- Removing unnecessary spaces.
- Ensuring uppercase formatting.

The values were already consistent.
"""

'\nThe rating column was standardized by:\n- Removing unnecessary spaces.\n- Ensuring uppercase formatting.\n\nThe values were already consistent.\n'

In [ ]:
df['rating'].value_counts()

rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [ ]:
df['rating'] = df['rating'].str.strip()
df['rating'] = df['rating'].str.upper()

print("Check the first 10 unique rating values to verify consistency after standardization")
print(df['rating'].unique()[:10])

Check the first 10 unique rating values to verify consistency after standardization
['PG-13' 'TV-MA' 'TV-PG' 'TV-14' 'TV-Y7' 'TV-Y' 'PG' 'TV-G' 'R' 'G']

In [ ]:
print("\n Check distribution")
df['rating'].value_counts()

 Check distribution

rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [ ]:
### Type Column Standardization
"""
The type column was checked for inconsistent category names.

The values were already standardized as:
- Movie
- TV Show
"""

'\nThe type column was checked for inconsistent category names.\n\nThe values were already standardized as:\n- Movie\n- TV Show\n'

In [ ]:
df['type'].value_counts()

type
Movie      6126
TV Show    2664
Name: count, dtype: int64

In [ ]:
from os import replace
df['type'] = df['type'].str.strip()
df['type'] = df['type'].replace(
    {
        'Tv Show':'TV Show',
        'tv Show':'TV Show',
        'movie':'Movie'

    }
)
print("Check the first 10 unique type values to verify consistency after standardization")
df['type'].unique()

Check the first 10 unique type values to verify consistency after standardization

array(['Movie', 'TV Show'], dtype=object)

In [ ]:
print("\n Check distribution")
df['type'].value_counts()

 Check distribution

type
Movie      6126
TV Show    2664
Name: count, dtype: int64

In [ ]:
## 6. Final Dataset Validation
"""
After cleaning and standardization, the dataset was checked again to ensure:
- No missing values.
- No duplicate records.
- Correct data formats.
"""
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
count,8790,8790,8790,8790,8790,8790,8790.000000,8790,8790,8790
unique,8790,2,8786,4528,86,1713,NaN,14,220,513
top,s8786,Movie,9-Feb,Not Given,United States,1/1/2020,NaN,TV-MA,1 Season,"Dramas, International Movies"
freq,1,6126,2,2588,3240,110,NaN,3205,1791,362
mean,NaN,NaN,NaN,NaN,NaN,NaN,2014.183163,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,8.825466,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN

In [ ]:
## 7. Export Clean Dataset
"""
The cleaned dataset was exported as a CSV file for further analysis and reporting.
"""

'\nThe cleaned dataset was exported as a CSV file for further analysis and reporting.\n'

In [ ]:
df.to_csv("netflix_cleaned.csv",index=False)

In [ ]:
## Conclusion
"""
The Netflix dataset was successfully cleaned and prepared for analysis.

Main steps completed:
- Dataset import and exploration.
- Missing values analysis.
- Duplicate records verification.
- Data standardization.
- Exporting the cleaned dataset.

The final dataset is ready for business analytics and visualization tasks.
"""

'\nThe Netflix dataset was successfully cleaned and prepared for analysis.\n\nMain steps completed:\n- Dataset import and exploration.\n- Missing values analysis.\n- Duplicate records verification.\n- Data standardization.\n- Exporting the cleaned dataset.\n\nThe final dataset is ready for business analytics and visualization tasks.\n'

In [ ]:
from google.colab import files

files.download("netflix_cleaned.csv")